# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- devel

pool:
  vmImage: 'ubuntu-18.04'

steps:
- script: |
    echo ""
    echo "==============================="
    echo "==== INSTALL STUFF VIA APT ===="
    echo "==============================="
    sudo apt-get update
    sudo apt-get install -y libgtk-3-dev
    sudo apt-get install -y libwebkit2gtk-4.0
    sudo apt-get install -y libwebkit2gtk-4.0-dev
    sudo apt-get install -y libcurl4-openssl-dev
    sudo apt-get install -y alsa
    sudp apt-get install -y alsa-tools
    sudo apt-get install -y libasound2-dev
    sudo apt-get install -y jack
    sudo apt-get install -y libjack-dev
    sudo apt-get install -y libfreetype6-dev
    sudo apt-get install -y libxinerama-dev
    sudo apt-get install -y libxcb-xinerama0
    sudo apt-get install -y libxinerama1
    sudo apt-get install -y x11proto-xinerama-dev
    sudo apt-get install -y libxrandr-dev
    sudo apt-get install -y libgl1-mesa-dev
    sudo apt-get install -y libxcursor-dev 
    sudo apt-get install -y libxcursor1 
    sudo apt-get install -y libxcb-cursor-dev 
    sudo apt-get install -y libxcb-cursor0
    sudo apt-get install -y xvfb
    sudo apt-get install -y lv2-dev 
    sudo apt-get install -y --fix-missing
    apt list --installed
  displayName: 'Install stuff with apt'

- script: |
    echo ""
    echo "==============================="
    echo "========= CLONE JUCE =========="
    echo "==============================="
    echo ""
    cd ..
    git clone -b lv2 https://github.com/lv2-porting-project/JUCE.git JUCE
    cd JUCE
    git log | grep 6.0.1
    echo "Checking out JUCE 6.0.1"
    git checkout a30f7357863a7d480a771e069abf56909cdf0e13
    echo ""
    echo "==============================="
    echo "======= BUILD PROJUCER ========"
    echo "==============================="
    echo ""
    cd extras/Projucer/Builds/LinuxMakefile
    make -j 8 CONFIG=Release
    echo "Set Projucer modules path"
    pwd
    export GDK_BACKEND=x11
    Xvfb :99 &
    export DISPLAY=:99
    sleep 5
    build/Projucer --set-global-search-path linux defaultJuceModulePath /home/vsts/work/1/JUCE/modules

  displayName: 'Set up JUCE'

- script: |
    echo ""
    echo "==============================="
    echo "======= EXPORT PROJUCER ======="
    echo "==============================="
    echo ""
    ../JUCE/extras/Projucer/Builds/LinuxMakefile/build/Projucer --resave Odin.jucer
    echo ""
    echo "==============================="
    echo "====== PREPARE LV2 STUFF ======"
    echo "==============================="
    echo ""
    cd JuceLibraryCode
    export LINE_NUMBER="$(grep -n 'BEGIN_USER_CODE_SECTION' AppConfig.h | cut -d: -f1)"
    echo "Line for usercode in AppConfig.h is $LINE_NUMBER"
    head -n $LINE_NUMBER AppConfig.h > app_config.tmp
    echo -e "#define JucePlugin_Build_LV2 1" >> app_config.tmp
    echo -e "#define JucePlugin_LV2URI \"https://www.thewavewarden.com/odin2\"" >> app_config.tmp
    echo -e "#define JucePlugin_MaxNumInputChannels 2" >> app_config.tmp
    echo -e "#define JucePlugin_MaxNumOutputChannels 2" >> app_config.tmp
    tail -n +$((LINE_NUMBER+1)) AppConfig.h >> app_config.tmp
    mv app_config.tmp AppConfig.h
    rm app_config.tmp
    echo ""
    echo "Contents of AppConfig.h after modification:"
    echo ""
    #cat AppConfig.h
    echo ""
    echo ""
    cd ..
    echo -e "include ../../LV2.mak" >> Builds/LinuxMakefile/Makefile
    #cat Builds/LinuxMakefile/Makefile
    echo ""
    echo "==============================="
    echo "========= Build Odin =========="
    echo "==============================="
    echo ""
    export PROJECT_VERSION="$(../JUCE/extras/Projucer/Builds/LinuxMakefile/build/Projucer --get-version Odin.jucer)"
    echo "Odin Project Version: $PROJECT_VERSION"
    echo $PROJECT_VERSION
    IFS='.' read -ra ADDR <<< "$PROJECT_VERSION"
    for i in "${ADDR[@]}"; do
      echo "$i"
    done
    pwd
    cd Builds/LinuxMakefile
    make -j 8 CONFIG=Release
  displayName: 'Build Odin2'
