# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- devel

pool:
  vmImage: 'ubuntu-18.04'

steps:
- script: |
    echo ""
    echo "==============================="
    echo "==== INSTALL STUFF VIA APT ===="
    echo "==============================="
    sudo apt-get update
    sudo apt-get install -y libgtk-3-dev
    sudo apt-get install -y libwebkit2gtk-4.0
    sudo apt-get install -y libwebkit2gtk-4.0-dev
    sudo apt-get install -y libcurl4-openssl-dev
    sudo apt-get install -y alsa
    sudp apt-get install -y alsa-tools
    sudo apt-get install -y libasound2-dev
    sudo apt-get install -y jack
    sudo apt-get install -y libjack-dev
    sudo apt-get install -y libfreetype6-dev
    sudo apt-get install -y libxinerama-dev
    sudo apt-get install -y libxcb-xinerama0
    sudo apt-get install -y libxinerama1
    sudo apt-get install -y x11proto-xinerama-dev
    sudo apt-get install -y libxrandr-dev
    sudo apt-get install -y libgl1-mesa-dev
    sudo apt-get install -y libxcursor-dev 
    sudo apt-get install -y libxcursor1 
    sudo apt-get install -y libxcb-cursor-dev 
    sudo apt-get install -y libxcb-cursor0
    sudo apt-get install -y --fix-missing
    apt list --installed
    echo ""
    echo "==============================="
    echo "========= CLONE JUCE =========="
    echo "==============================="
    pwd
    ls -la
    cd ..
    ls -la
    git clone https://github.com/juce-framework/JUCE.git
    cd JUCE
    echo "Checking out JUCE 6.0.1"
    git checkout a30f7357863a7d480a771e069abf56909cdf0e13
    echo ""
    echo "==============================="
    echo "======= BUILD PROJUCER ========"
    echo "==============================="
    cd extras/Projucer/Builds/LinuxMakefile
    make CONFIG=Release
  displayName: 'Build the project'
